version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.txt
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dbzin
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: dbzin
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: dbzin
      POSTGRES_USER: username
      POSTGRES_PASSWORD: dbzin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
